version: '3'
services:
  web:
    build:
      context: .
    command: go run main.go
    environment:
      DB_HOST: db
    volumes:
      - app_gopath:/go
      - .:/go/src/app
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  app_gopath:
    driver: local
  db_data:
    driver: local
